from __future__ import annotations

import os

import pytest

from pr_review_agent.diff_parser import parse_diff
from pr_review_agent.orchestrator import ReviewOrchestrator
from pr_review_agent.report import render_markdown
from tests.conftest import load_fixture


@pytest.fixture(autouse=True)
def _no_openai_key(monkeypatch):
    """The whole test suite must run fully offline: make sure a stray
    OPENAI_API_KEY in the developer's shell never causes a test to try a
    real network call."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)


def test_render_markdown_structure_for_vulnerable_fixture():
    file_diffs = parse_diff(load_fixture("vulnerable.diff"))
    result = ReviewOrchestrator(parallel=False).review(file_diffs)
    markdown = render_markdown(result, pr_title="Add new features", repo="octo/demo", pr_number=42)

    assert markdown.startswith("# 🤖 AI PR Review")
    assert "octo/demo#42" in markdown
    assert "## Executive Summary" in markdown
    assert "## Summary" in markdown
    assert "## Findings" in markdown
    assert "| Severity | Count |" in markdown
    assert "Verdict: **Request Changes**" in markdown
    assert "app/config.py" in markdown
    assert "app/utils.py" in markdown
    assert "Generated by [AI PR Review Agent]" in markdown


def test_render_markdown_clean_diff_has_no_issues_message():
    file_diffs = parse_diff(load_fixture("clean.diff"))
    result = ReviewOrchestrator(parallel=False).review(file_diffs)
    markdown = render_markdown(result)

    assert "No issues found by any analyzer." in markdown
    assert "Verdict: **Approve**" in markdown


def test_render_markdown_includes_pr_url_when_given():
    file_diffs = parse_diff(load_fixture("clean.diff"))
    result = ReviewOrchestrator(parallel=False).review(file_diffs)
    markdown = render_markdown(result, pr_url="https://github.com/octo/demo/pull/42")

    assert "https://github.com/octo/demo/pull/42" in markdown
