"""Renders a :class:`~pr_review_agent.orchestrator.ReviewResult` to markdown."""

from __future__ import annotations

from collections import defaultdict

from pr_review_agent.analyzers.base import Finding, Severity
from pr_review_agent.llm import generate_executive_summary
from pr_review_agent.orchestrator import ReviewResult

_SEVERITY_ORDER = (
    Severity.CRITICAL,
    Severity.HIGH,
    Severity.MEDIUM,
    Severity.LOW,
    Severity.INFO,
)


def render_markdown(
    result: ReviewResult,
    pr_title: str | None = None,
    pr_url: str | None = None,
    repo: str | None = None,
    pr_number: int | None = None,
) -> str:
    """Render the full review as a markdown document.

    Sections: title/verdict banner, executive summary, severity summary
    table, findings grouped by file, and a footer listing which analyzers
    ran.
    """
    lines: list[str] = []

    header = "# 🤖 AI PR Review"
    if repo and pr_number:
        header += f" (`{repo}#{pr_number}`)"
    lines.append(header)
    lines.append("")
    lines.append(f"### {result.verdict.emoji} Verdict: **{result.verdict.label}**")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(generate_executive_summary(result, pr_title))
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Files reviewed:** {result.files_reviewed}")
    lines.append(f"- **Analyzers run:** {', '.join(result.analyzers_run)}")
    lines.append(f"- **Total findings:** {len(result.findings)}")
    lines.append("")
    lines.append(_severity_table(result))
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    if not result.findings:
        lines.append("No issues found by any analyzer. 🎉")
        lines.append("")
    else:
        lines.append(_findings_by_file(result.findings))

    lines.append("---")
    lines.append(
        "*Generated by [AI PR Review Agent]"
        "(https://github.com/laharidilli/ai-pr-review-agent). "
        f"Analyzers: {', '.join(result.analyzers_run)}.*"
    )
    if pr_url:
        lines.append(f"*Pull request: {pr_url}*")

    return "\n".join(lines).rstrip() + "\n"


def _severity_table(result: ReviewResult) -> str:
    rows = ["| Severity | Count |", "|---|---|"]
    for severity in _SEVERITY_ORDER:
        count = result.severity_counts.get(severity, 0)
        rows.append(f"| {severity.emoji} {severity.label} | {count} |")
    return "\n".join(rows)


def _findings_by_file(findings: list[Finding]) -> str:
    by_file: dict[str, list[Finding]] = defaultdict(list)
    for f in findings:
        by_file[f.file].append(f)

    out: list[str] = []
    for path in sorted(by_file):
        file_findings = sorted(
            by_file[path], key=lambda f: (-f.severity.value, f.line or 0)
        )
        out.append(f"### `{path}`")
        out.append("")
        for f in file_findings:
            loc = f"line {f.line}" if f.line else "file-level"
            out.append(f"- {f.severity.emoji} **{f.severity.label}** ({f.analyzer}, {loc}): {f.message}")
            if f.suggestion:
                out.append(f"  - *Suggestion:* {f.suggestion}")
        out.append("")
    return "\n".join(out)
